version: "3"

volumes:
  minio-data:
  mongo-data:

services:
    mohsen-zookeeper:
      container_name: mohsen-zookeeper
      image: confluentinc/cp-zookeeper:5.2.5
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
       - "2181:2181"
      volumes:
        - ./data/zookeeper/data:/data
        - ./data/zookeeper/datalog:/datalog
    mohsen-mongo:
      container_name: mohsen-mongo
      image: mongo:5.0.3
      ports:
        - 27017:27017
      volumes:
        - "mongo-data:/data/db"
      environment:
        - MONGO_INITDB_DATABASE=test_db
        - MONGO_INITDB_ROOT_USERNAME=mohsen
        - MONGO_INITDB_ROOT_PASSWORD=123
    mohsen-redis:
      container_name: mohsen-redis
      image: redis:6.2.6
      restart: always
      ports:
        - "6379:6379"
    mohsen-kafka:
      image: confluentinc/cp-kafka:5.2.5
      container_name: mohsen-kafka
      ports:
        - 9092:9092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: mohsen-zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://mohsen-kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      volumes:
         - ./data/kafka1/data:/var/lib/kafka/data
      depends_on:
        - mohsen-zookeeper
    mohsen-kafdrop:
      image: obsidiandynamics/kafdrop
      container_name: mohsen-kafdrop
      restart: "no"
      ports:
        - "9003:9000"
      environment:
        KAFKA_BROKERCONNECT: "mohsen-kafka:29092"
      depends_on:
        - mohsen-kafka
    mohsen-gateway:
        container_name: mohsen-gateway
        build:
          context: ../mohsen_backend_gateway
          dockerfile: Dockerfile
        command: [
         "sh",
         "-c",
         "/usr/local/wait-for-it.sh mohsen-redis:6379  &&
         python app.py"]
         
        volumes:
          - ../mohsen_backend_gateway/app:/app
        ports:
          - "5001:5000"
        depends_on:
          - mohsen-redis
        env_file:
          - .env
    mohsen-user:
        container_name: mohsen-user
        build:
          context: ../mohsen_backend_user
          dockerfile: Dockerfile
        command: [
         "sh",
         "-c",
         "/usr/local/wait-for-it.sh mohsen-mongo:27017  &&
         python app.py"]
        volumes:
          - ../mohsen_backend_user/app:/app
        ports:
          - "5002:5000"
        depends_on:
          - mohsen-mongo
        env_file:
          - .env
    mohsen-consumer:
        container_name: mohsen-consumer
        restart: always
        build:
          context: ../mohsen_backend_consumer
          dockerfile: Dockerfile
        command: [
         "sh",
         "-c",
         "/usr/local/wait-for-it.sh mohsen-mongo:27017  &&
         python app.py"]
        #  "/usr/local/wait-for-it.sh mohsen-kafka:29092  &&
        volumes:
          - ../mohsen_backend_consumer/app:/app
        depends_on:
          - mohsen-mongo
        env_file:
          - .env